---
- name: resolve platform specific vars
  include_vars: "{{item}}"
  with_first_found:
    - files:
      - "{{ansible_distribution}}-{{ansible_distribution_release}}.yml"
      - "{{ansible_distribution}}.yml"
      - "{{ansible_os_family}}.yml"
      skip: true

- name: check if the device has partition layout
  become: true
  become_user: root
  command: sfdisk -d {{provision_thinpool_device_name}}
  register: partition_layout

- name: run tasks to provision thinpool
  when: partition_layout.stdout == ""
  include: provision-tasks.yml
